# Generated by Django 5.2.5 on 2025-08-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop", "0003_vocab"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                ("cohort_id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "cohort",
            },
        ),
        migrations.CreateModel(
            name="CohortAttribute",
            fields=[
                (
                    "cohort_attribute_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "cohort_attribute",
            },
        ),
        migrations.CreateModel(
            name="ConditionEra",
            fields=[
                (
                    "condition_era_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "condition_era",
            },
        ),
        migrations.CreateModel(
            name="DoseEra",
            fields=[
                ("dose_era_id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "dose_era",
            },
        ),
        migrations.CreateModel(
            name="DrugEra",
            fields=[
                ("drug_era_id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "drug_era",
            },
        ),
        migrations.CreateModel(
            name="FactRelationship",
            fields=[
                (
                    "fact_relationship_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "fact_relationship",
            },
        ),
        migrations.CreateModel(
            name="Metadata",
            fields=[
                ("metadata_id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "metadata",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("note_id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "note",
            },
        ),
        migrations.CreateModel(
            name="NoteNlp",
            fields=[
                ("note_nlp_id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "note_nlp",
            },
        ),
        migrations.CreateModel(
            name="Specimen",
            fields=[
                ("specimen_id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "specimen",
            },
        ),
        migrations.CreateModel(
            name="VisitDetail",
            fields=[
                (
                    "visit_detail_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "visit_detail",
            },
        ),
    ]
