# Generated by Django 5.2.5 on 2025-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop", "0004_cohort_cohortattribute_conditionera_doseera_drugera_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="location",
        ),
        migrations.AddField(
            model_name="person",
            name="birth_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="care_site_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="ethnicity_source_concept_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="ethnicity_source_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="gender_source_concept_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="gender_source_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="location_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="person_source_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="provider_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="race_source_concept_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="race_source_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender_concept_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="person_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
